<script lang="ts">
	import { toast } from 'svelte-sonner';

	import { createEventDispatcher, onMount, getContext } from 'svelte';
	import { config, models } from '$lib/stores';
	import Tags from '$lib/components/common/Tags.svelte';

	const i18n = getContext('i18n');

	const dispatch = createEventDispatcher();

	export let message;
	export let show = false;

	let LIKE_REASONS: string[] = [
		'clear_explanation',
		'helpful_teaching_approach',
		'effective_learning_guidance',
		'solved_my_problem',
		'well_structured_answer',
		'encouraged_critical_thinking',
		'other'
	];
	let DISLIKE_REASONS: string[] = [
		'confusing_explanation',
		'too_complex',
		'too_simplistic',
		'didnt_address_my_question',
		'needs_more_examples',
		'not_helpful_for_learning',
		'other'
	];

	let tags: { name: string }[] = [];

	let reasons: string[] = [];
	let selectedReason: string | null = null;
	let comment = '';

	let detailedRating: number | null = null;
	let selectedModel: any = null;

	// Define emoji representations for ratings 1-10
	const emojiRatings = [
		'😖', // 1 - Not helpful
		'😟', // 2
		'😕', // 3
		'😐', // 4
		'🙂', // 5
		'😊', // 6
		'😄', // 7
		'😁', // 8
		'🤩', // 9
		'🌟' // 10 - Very helpful
	];

	let isSubmitting = false;

	$: if (message?.annotation?.rating === 1) {
		reasons = LIKE_REASONS;
	} else if (message?.annotation?.rating === -1) {
		reasons = DISLIKE_REASONS;
	}

	$: if (message) {
		init();
	}

	const init = () => {
		if (!selectedReason) {
			selectedReason = message?.annotation?.reason ?? '';
		}

		if (!comment) {
			comment = message?.annotation?.comment ?? '';
		}

		tags = (message?.annotation?.tags ?? []).map((tag: string) => ({
			name: tag
		}));

		if (!detailedRating) {
			detailedRating = message?.annotation?.details?.rating ?? null;
		}
	};

	onMount(() => {
		if (message?.arena) {
			selectedModel = $models.find((m) => m.id === message.selectedModelId);
			toast.success(
				$i18n.t('This response was generated by "{{model}}"', {
					model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
				})
			);
		}
	});

	const saveHandler = () => {
		console.log('saveHandler');
		// if (!selectedReason) {
		// 	toast.error($i18n.t('Please select a reason'));
		// 	return;
		// }

		isSubmitting = true;

		dispatch('save', {
			reason: selectedReason,
			comment: comment,
			tags: tags.map((tag) => tag.name),
			details: {
				rating: detailedRating
			}
		});

		toast.success($i18n.t('Thanks for your feedback!'));
		show = false;
		setTimeout(() => {
			isSubmitting = false;
		}, 300);
	};
</script>

{#if message?.arena}
	<div class="text-xs font-medium pt-1.5 -mb-0.5">
		{$i18n.t('This response was generated by "{{model}}"', {
			model: selectedModel ? (selectedModel?.name ?? selectedModel.id) : message.selectedModelId
		})}
	</div>
{/if}

<div
	class=" m-6 rounded-xl p-4 border border-gray-100 dark:border-gray-850"
	id="message-feedback-{message.id}"
>
	<div class="flex justify-between items-center">
		<div class="text-sm font-medium">
			{$i18n.t('How helpful was this response for your learning?')}
		</div>

		<button
			on:click={() => {
				show = false;
			}}
		>
			<svg
				xmlns="http://www.w3.org/2000/svg"
				fill="none"
				viewBox="0 0 24 24"
				stroke-width="1.5"
				stroke="currentColor"
				class="size-4"
			>
				<path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
			</svg>
		</button>
	</div>

	<div class="w-full flex justify-center">
		<div class=" relative w-fit">
			<div class="mt-5 w-fit flex gap-5 pb-6">
				{#if message?.annotation?.rating === -1}
					{#each Array.from({ length: 5 }).map((_, i) => i + 1) as rating}
						<button
							class="size-6 text-lg border border-gray-200 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
							rating
								? 'bg-yellow-400 dark:bg-gray-100'
								: ''} transition-all duration-150 transform active:scale-90 hover:shadow rounded-full flex items-center justify-center p-0.5"
							on:click={() => {
								detailedRating = rating;
							}}
							title={`Rating: ${rating}`}
						>
							{emojiRatings[rating - 1]}
						</button>
					{/each}
				{:else if message?.annotation?.rating === 1}
					{#each Array.from({ length: 5 }).map((_, i) => i + 6) as rating}
						<button
							class="size-6 text-lg border border-gray-100 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {detailedRating ===
							rating
							? 'bg-yellow-400 dark:bg-gray-100'
							: ''} transition-all duration-150 transform active:scale-90 hover:shadow rounded-full disabled:cursor-not-allowed disabled:opacity-50 disabled:bg-white dark:disabled:bg-gray-900 flex items-center justify-center p-1"
							on:click={() => {
								detailedRating = rating;
							}}
							title={`Rating: ${rating}`}
						>
							{emojiRatings[rating - 1]}
						</button>
					{/each}
				{/if}
			</div>

			<div class="absolute bottom-0 left-0 right-0 flex justify-between text-xs mt-1.5 px-1">
				{#if message?.annotation?.rating === -1}
					<div>
						{emojiRatings[0]} - {$i18n.t('Not helpful')}
					</div>
					<div>
						{emojiRatings[4]} - {$i18n.t('Less helpful')}
					</div>
				{:else if message?.annotation?.rating === 1}
					<div>
						{emojiRatings[5]} - {$i18n.t('Helpful')}
					</div>
					<div>
						{emojiRatings[9]} - {$i18n.t('Very helpful')}
					</div>
				{/if}
			</div>
		</div>
	</div>

	<div>
		{#if reasons.length > 0}
			<div class="text-sm mt-4 font-medium">{$i18n.t('Why?')}</div>

			<div class="flex flex-wrap gap-1.5 text-sm mt-1.5">
				{#each reasons as reason}
					<button
						class="px-3 py-0.5 border border-gray-100 dark:border-gray-850 hover:bg-gray-50 dark:hover:bg-gray-850 {selectedReason ===
						reason
							? 'bg-gray-100 dark:bg-gray-800'
							: ''} transition rounded-xl"
						on:click={() => {
							selectedReason = reason;
						}}
					>
						{#if reason === 'clear_explanation'}
							{$i18n.t('Clear explanation')}
						{:else if reason === 'helpful_teaching_approach'}
							{$i18n.t('Helpful teaching approach')}
						{:else if reason === 'effective_learning_guidance'}
							{$i18n.t('Effective learning guidance')}
						{:else if reason === 'solved_my_problem'}
							{$i18n.t('Solved my problem')}
						{:else if reason === 'well_structured_answer'}
							{$i18n.t('Well structured answer')}
						{:else if reason === 'encouraged_critical_thinking'}
							{$i18n.t('Encouraged critical thinking')}
						{:else if reason === 'confusing_explanation'}
							{$i18n.t('Confusing explanation')}
						{:else if reason === 'too_complex'}
							{$i18n.t('Too complex')}
						{:else if reason === 'too_simplistic'}
							{$i18n.t('Too simplistic')}
						{:else if reason === 'didnt_address_my_question'}
							{$i18n.t("Didn't address my question")}
						{:else if reason === 'needs_more_examples'}
							{$i18n.t('Needs more examples')}
						{:else if reason === 'not_helpful_for_learning'}
							{$i18n.t('Not helpful for learning')}
						{:else if reason === 'other'}
							{$i18n.t('Other')}
						{:else}
							{reason}
						{/if}
					</button>
				{/each}
			</div>
		{/if}
	</div>

	<div class="mt-2">
		<textarea
			bind:value={comment}
			class="w-full text-sm px-1 py-2 bg-transparent outline-hidden resize-none rounded-xl"
			placeholder={$i18n.t(
				'How could this response be improved for your learning? Feel free to share your thoughts!🤗'
			)}
			rows="3"
		/>
	</div>

	<div class="mt-2 gap-1.5 flex justify-between">
		<div class="flex items-end group">
			<Tags
				{tags}
				on:delete={(e) => {
					tags = tags.filter(
						(tag) =>
							tag.name.replaceAll(' ', '_').toLowerCase() !==
							e.detail.replaceAll(' ', '_').toLowerCase()
					);
				}}
				on:add={(e) => {
					tags = [...tags, { name: e.detail }];
				}}
			/>
		</div>

		<button
			class="px-3.5 py-1.5 text-sm font-medium bg-black hover:bg-gray-900 text-white dark:bg-white dark:text-black dark:hover:bg-gray-100 transition rounded-xl z-50"
			on:click={() => {
				saveHandler();
			}}
		>
			{$i18n.t('Save')}
		</button>
	</div>
</div>