"""add_ended_at_to_class_sessions

Revision ID: d020e02dee83
Revises: 3aabdff2eab4
Create Date: 2026-06-20 13:13:17.161678

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "d020e02dee83"
down_revision: Union[str, None] = "3aabdff2eab4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("class_sessions", sa.Column("ended_at", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("class_sessions", "ended_at")
    # ### end Alembic commands ###
